### ISSUE TITLE
Video Conditioning

### ISSUE THREAD

**Issue by ttaosci** [basilevh/gcd#6]
I have a question about the GCD's video conditioning mechanism:
Why does it concatenate a noisy version of the input video with the clean version before sending it to U-Net? Can’t we just use the clean version's latent representation? What’s the benefit of including the noisy version?

Thank you for your help!

**Comment by basilevh** [comment]
Hi! Just to clarify, do you mean the sample that is being denoised (output video from the destination viewpoint), or the input video from the source viewpoint that conditions the model?

**Comment by ttaosci** [comment]
I mean the input video from the source view. Thanks!

**Comment by basilevh** [comment]
Sure! This is called conditioning augmentation and is controlled by `cond_aug`, the value is typically quite low (0.02 in our case). It was introduced in earlier papers to avoid accumulating errors when diffusion models are applied in a cascaded fashion. Even though we do not apply the model recursively here, SVD has it enabled by default so I decided to simply leave it on as well. Intuitively it can be regarded as a form of data augmentation, since our dataset is not that big. Hope this helps!

**Comment by ttaosci** [comment]
Thanks for the clear explanation!
